# Libraries

In [5]:
import numpy as np

In [5]:
!conda install numpy

Channels:
 - defaults
Platform: win-64
Solving environment: ...working... done

# All requested packages already installed.



# Create Array

In [60]:
egg_box = np.array(['chicken_egg', 'country_egg', 'quail_egg'])

In [61]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [62]:
egg_box.shape

(3,)

In [63]:
egg_box.ndim

1

# Array dimensions (0-d, 1-d, 2-d, 3d)

In [64]:
egg_box_zero = np.array('egg')

In [65]:
egg_box_zero.ndim

0

In [66]:
egg_box_zero.shape

()

In [125]:
egg_box_two = np.array([['chicken_egg', 'country_egg', 'quail_egg'],['chicken_egg', 'country_egg', 'quail_egg']])

In [68]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [124]:
egg_box_3 = np.array([[['chicken_egg', 'country_egg', 'quail_egg'],['chicken_egg', 'country_egg', 'quail_egg']], 
                      [['chicken_egg', 'country_egg', 'quail_egg'],['chicken_egg', 'country_egg', 'quail_egg']]])

In [70]:
egg_box_3

array([[['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']],

       [['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']]], dtype='<U11')

In [73]:
egg_box_two.ndim

2

In [74]:
egg_box_two.shape

(2, 3)

In [75]:
egg_box_3.shape

(2, 2, 3)

# Array operations (statistics methods, arithmetic, logical, expo, sqrt, sine)

In [176]:
a = np.array([1,2,3])
a^2

array([3, 0, 1])

In [184]:
np.std(a)

np.float64(0.816496580927726)

In [7]:
array =  np.array([1,2,3])


# Compute the statistical values
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Mean: 2.0
Median: 2.0
Standard Deviation: 0.816496580927726
Variance: 0.6666666666666666


In [11]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

Original matrix:
[[ 7  8 10]
 [10  8  4]
 [ 5  1  1]]
Determinant: -192.0
Inverse:
[[-0.02083333 -0.01041667  0.25      ]
 [-0.05208333  0.22395833 -0.375     ]
 [ 0.15625    -0.171875    0.125     ]]


In [13]:
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[ 9  8  4  7]
 [10  3  9  8]
 [ 4  8  5  8]]
Array 2:
[[6 9 1 9]
 [1 5 2 9]
 [3 6 1 7]]
Element-wise addition:
[[15 17  5 16]
 [11  8 11 17]
 [ 7 14  6 15]]
Element-wise subtraction:
[[ 3 -1  3 -2]
 [ 9 -2  7 -1]
 [ 1  2  4  1]]
Element-wise multiplication:
[[54 72  4 63]
 [10 15 18 72]
 [12 48  5 56]]
Element-wise division:
[[ 1.5         0.88888889  4.          0.77777778]
 [10.          0.6         4.5         0.88888889]
 [ 1.33333333  1.33333333  5.          1.14285714]]


# Array modification

In [100]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [102]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

### numpy.insert(arr, obj, values, axis=None)

In [121]:
np.insert(egg_box, 1, 'duck_egg')

array(['chicken_egg', 'duck_egg', 'country_egg', 'quail_egg'],
      dtype='<U11')

In [128]:
np.insert(egg_box_two, 1, 'duck_egg', axis=1)

array([['chicken_egg', 'duck_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'duck_egg', 'country_egg', 'quail_egg']],
      dtype='<U11')

In [123]:
np.insert(egg_box_two, 2, 'dinosaur_egg')

array(['chicken_egg', 'country_egg', 'dinosaur_eg', 'quail_egg',
       'chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [129]:
np.insert(egg_box_two, 1, 'dino_egg', axis=0)

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['dino_egg', 'dino_egg', 'dino_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

### numpy.delete(arr, obj, axis=None)[source]

In [144]:
egg_box_copy = np.delete(egg_box, 2)

In [142]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [146]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [145]:
egg_box_copy

array(['chicken_egg', 'country_egg'], dtype='<U11')

### numpy.append(arr, values, axis=None)

In [130]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [131]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [132]:
np.append(egg_box, 'duck_egg')

array(['chicken_egg', 'country_egg', 'quail_egg', 'duck_egg'],
      dtype='<U11')

# Access array elements (Indexing, slicing)

In [76]:
egg_box 

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [77]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [78]:
egg_box_3

array([[['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']],

       [['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']]], dtype='<U11')

In [86]:
egg_box[-3]

np.str_('chicken_egg')

In [82]:
egg_box_two[1,1]

np.str_('country_egg')

In [84]:
egg_box_3[1,1,2]

np.str_('quail_egg')

## array[start : stop: step]

In [87]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [88]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [98]:
egg_box[0:10:2]

array(['chicken_egg', 'quail_egg'], dtype='<U11')

In [99]:
egg_box_two[0:1]

array([['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

# Array reshape

### 1d to 2d

In [151]:
egg_box = np.append(egg_box, 'duck_egg')

In [152]:
egg_box.shape

(4,)

In [153]:
egg_box.reshape(2,2)

array([['chicken_egg', 'country_egg'],
       ['quail_egg', 'duck_egg']], dtype='<U11')

### 1d to 3d

In [161]:
egg_box.reshape(2,2,2)

array([[['chicken_egg', 'country_egg'],
        ['quail_egg', 'duck_egg']],

       [['chicken_egg', 'country_egg'],
        ['quail_egg', 'duck_egg']]], dtype='<U11')

In [160]:
egg_box = np.array(['chicken_egg', 'country_egg', 'quail_egg', 'duck_egg', 'chicken_egg', 'country_egg', 'quail_egg', 'duck_egg'])

# Array iteration

In [164]:
egg_box 

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [165]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [166]:
for i in egg_box:
    print("I am ", i)

I am  chicken_egg
I am  country_egg
I am  quail_egg


In [168]:
for i in egg_box_two:
    for j in i:
        print("I am ", j)

I am  chicken_egg
I am  country_egg
I am  quail_egg
I am  chicken_egg
I am  country_egg
I am  quail_egg


In [171]:
for i in np.nditer(egg_box_two):
    print("I am ", i)

I am  chicken_egg
I am  country_egg
I am  quail_egg
I am  chicken_egg
I am  country_egg
I am  quail_egg


In [172]:
for idx, i in np.ndenumerate(egg_box_two):
    print("index", idx)
    print("I am ", i)

index (0, 0)
I am  chicken_egg
index (0, 1)
I am  country_egg
index (0, 2)
I am  quail_egg
index (1, 0)
I am  chicken_egg
index (1, 1)
I am  country_egg
index (1, 2)
I am  quail_egg


# Array joining

In [187]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [188]:
egg_box_new = np.array([['egg1', 'egg2', 'egg3'],['egg4', 'egg5', 'egg6']])

In [189]:
egg_box_new

array([['egg1', 'egg2', 'egg3'],
       ['egg4', 'egg5', 'egg6']], dtype='<U4')

### hstack - row

In [191]:
np.hstack((egg_box_two, egg_box_new))

array([['chicken_egg', 'country_egg', 'quail_egg', 'egg1', 'egg2',
        'egg3'],
       ['chicken_egg', 'country_egg', 'quail_egg', 'egg4', 'egg5',
        'egg6']], dtype='<U11')

### vstack - column

In [192]:
np.vstack((egg_box_two, egg_box_new))

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg'],
       ['egg1', 'egg2', 'egg3'],
       ['egg4', 'egg5', 'egg6']], dtype='<U11')

### dstack

In [193]:
np.dstack((egg_box_two, egg_box_new))

array([[['chicken_egg', 'egg1'],
        ['country_egg', 'egg2'],
        ['quail_egg', 'egg3']],

       [['chicken_egg', 'egg4'],
        ['country_egg', 'egg5'],
        ['quail_egg', 'egg6']]], dtype='<U11')

# Array splitting

In [196]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [203]:
np.array_split(egg_box, 4)

[array(['chicken_egg'], dtype='<U11'),
 array(['country_egg'], dtype='<U11'),
 array(['quail_egg'], dtype='<U11'),
 array([], dtype='<U11')]

#### hsplit(), vsplit(), dsplit() are also there

# Copy vs view

In [210]:
egg_box_copy = egg_box.copy()
egg_box_view = egg_box.view()

In [211]:
egg_box_copy

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [212]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [213]:
egg_box_view[0] = 'duck_egg'

In [214]:
egg_box_view

array(['duck_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [215]:
egg_box

array(['duck_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [216]:
egg_box_copy[1] = 'dino_egg'

In [217]:
egg_box

array(['duck_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [15]:
my_list = [1,2,3,4,5]
my_list + 1

TypeError: can only concatenate list (not "int") to list

In [17]:
my_array = np.array([1,2,3,4,5])
my_array+1

array([2, 3, 4, 5, 6])